import * as THREE from 'three'

import { computeRosettePositions } from './scaffoldGeometry'
import { UNIVERSAL_RINGLOCK_STANDARDS, type UniversalRinglockStandardId } from './ringlockCatalog'
import { findClosestLedger, UNIVERSAL_LEDGER_LENGTHS, type ScaffoldBlockInstance } from '../../types/scaffoldGraph'

function clampFiniteNumber(v: unknown, fallback: number): number {
	const n = Number(v)
	return Number.isFinite(n) ? n : fallback
}

function roundPositionKeyValue(value: number, precision = 1000): number {
	return Math.round(value * precision) / precision
}

export function rotateOffset90(o: { x: number; y: number }, steps: number): { x: number; y: number } {
	const rawSteps = Number(steps)
	if (!Number.isFinite(rawSteps)) return { x: o.x, y: o.y }
	const roundedSteps = Math.round(rawSteps)
	if (Math.abs(rawSteps - roundedSteps) <= 1e-6) {
		const s = ((roundedSteps % 4) + 4) % 4
		if (s === 0) return { x: o.x, y: o.y }
		if (s === 1) return { x: -o.y, y: o.x }
		if (s === 2) return { x: -o.x, y: -o.y }
		return { x: o.y, y: -o.x }
	}
	const angle = rawSteps * (Math.PI / 2)
	const cos = Math.cos(angle)
	const sin = Math.sin(angle)
	return {
		x: o.x * cos - o.y * sin,
		y: o.x * sin + o.y * cos,
	}
}

export function posKey2(x: number, y: number, precision = 1000): string {
	// precision=1000 => millifeet buckets (~0.012") to stabilize float comparisons.
	const kx = roundPositionKeyValue(x, precision)
	const ky = roundPositionKeyValue(y, precision)
	return `${kx}:${ky}`
}

export function makeStackPositionKey(x: number, y: number, z: number, precision = 1000): string {
	const planKey = posKey2(x, y, precision)
	const kz = roundPositionKeyValue(z, precision)
	return Math.abs(kz) <= 1 / precision ? planKey : `${planKey}:${kz}`
}

export function parseStackPositionKey(key: string, precision = 1000): {
	x: number
	y: number
	z: number
	planKey: string
	exactKey: string
} | null {
	const parts = String(key).split(':')
	if (parts.length !== 2 && parts.length !== 3) return null

	const [rawX, rawY, rawZ] = parts
	const x = Number(rawX)
	const y = Number(rawY)
	const z = rawZ === undefined ? 0 : Number(rawZ)
	if (!Number.isFinite(x) || !Number.isFinite(y) || !Number.isFinite(z)) return null

	return {
		x: roundPositionKeyValue(x, precision),
		y: roundPositionKeyValue(y, precision),
		z: roundPositionKeyValue(z, precision),
		planKey: posKey2(x, y, precision),
		exactKey: makeStackPositionKey(x, y, z, precision),
	}
}

export function makeBlockLiveLoadBayKey(liftIndex: number, bayX: number, bayY: number): string {
	return `${Math.round(liftIndex)}:${Math.round(bayX)}:${Math.round(bayY)}`
}

export function chooseBayLayout(totalFt: number): { bays: number; spacingFt: number; ledgerPartNumber: string } {
	const safeTotalFt = Math.max(0.1, clampFiniteNumber(totalFt, 7))
	// Practical guard: avoid ultra-short bays unless the whole dimension is short.
	const minSpacingFt = 2
	// Typical ringlock planning target: ~7ft bays.
	const targetSpacingFt = 7
	const maxBays = Math.min(20, Math.max(1, Math.ceil(safeTotalFt / minSpacingFt)))

	let bestBays = 1
	let bestSpacingFt = safeTotalFt
	let bestPart = findClosestLedger(safeTotalFt * 12, 6, false) ?? 'UH70'
	let bestScore = Number.POSITIVE_INFINITY

	for (let bays = 1; bays <= maxBays; bays++) {
		const spacingFt = safeTotalFt / bays
		if (bays > 1 && spacingFt < minSpacingFt - 1e-6) continue
		const spacingIn = spacingFt * 12
		const part = findClosestLedger(spacingIn, 6, false) ?? 'UH70'
		const partLenIn = UNIVERSAL_LEDGER_LENGTHS[part]
		const diffIn = typeof partLenIn === 'number' ? Math.abs(partLenIn - spacingIn) : 0
		// Prefer a professional default: bay spacing near ~7ft and fewer bays (fewer standards).
		// Ledger length matching is a secondary tie-break (ledgers scale visually anyway).
		const spacingPenalty = Math.abs(spacingFt - targetSpacingFt) * 8
		const baysPenalty = bays * 10
		const ledgerPenalty = diffIn * 0.25
		const score = spacingPenalty + baysPenalty + ledgerPenalty
		if (score < bestScore) {
			bestScore = score
			bestBays = bays
			bestSpacingFt = spacingFt
			bestPart = part
		}
	}

	return { bays: bestBays, spacingFt: bestSpacingFt, ledgerPartNumber: bestPart }
}

type BayLayout = ReturnType<typeof chooseBayLayout>

export function resolveBlockDeckPlan(
	block: Pick<
		ScaffoldBlockInstance,
		'depthFt'
		| 'autoGeneratedMode'
		| 'autoGeneratedTargetShape'
		| 'autoGeneratedRoundInnerLedgerFt'
	>,
	layoutX: BayLayout,
	layoutY: BayLayout,
): {
	runAlongX: boolean
	runLengthFt: number
	crossSpanFt: number
	crossLedgerPartNumber: string
	runAnchor: 'center' | 'positive'
} {
	const isRoundAutoBay = (
		block.autoGeneratedMode === 'around-building'
		&& (block.autoGeneratedTargetShape === 'circle' || block.autoGeneratedTargetShape === 'ring')
		&& Number.isFinite(Number(block.autoGeneratedRoundInnerLedgerFt))
	)
	if (isRoundAutoBay) {
		const crossSpanFt = Math.max(0.1, Number(block.autoGeneratedRoundInnerLedgerFt))
		return {
			runAlongX: false,
			runLengthFt: Math.max(0.1, Number(block.depthFt) || 0.1),
			crossSpanFt,
			crossLedgerPartNumber: findClosestLedger(crossSpanFt * 12, 6, false) ?? layoutX.ledgerPartNumber,
			runAnchor: 'positive',
		}
	}

	const runAlongX = layoutX.spacingFt >= layoutY.spacingFt
	const crossSpanFt = runAlongX ? layoutY.spacingFt : layoutX.spacingFt
	return {
		runAlongX,
		runLengthFt: runAlongX ? layoutX.spacingFt : layoutY.spacingFt,
		crossSpanFt,
		crossLedgerPartNumber: runAlongX ? layoutY.ledgerPartNumber : layoutX.ledgerPartNumber,
		runAnchor: 'center',
	}
}

export function resolveRoundAutoBayFrame(
	block: Pick<
		ScaffoldBlockInstance,
		'managedStackKeys'
		| 'autoGeneratedMode'
		| 'autoGeneratedTargetShape'
	>,
): {
	origin: { x: number; y: number }
	tangent: { x: number; y: number }
	inward: { x: number; y: number }
} | null {
	const isRoundAutoBay = (
		block.autoGeneratedMode === 'around-building'
		&& (block.autoGeneratedTargetShape === 'circle' || block.autoGeneratedTargetShape === 'ring')
	)
	if (!isRoundAutoBay) return null

	const [innerKeyA, innerKeyB, outerKeyA, outerKeyB] = block.managedStackKeys ?? []
	if (!innerKeyA || !innerKeyB || !outerKeyA || !outerKeyB) return null

	const innerA = parseStackPositionKey(innerKeyA)
	const innerB = parseStackPositionKey(innerKeyB)
	const outerA = parseStackPositionKey(outerKeyA)
	const outerB = parseStackPositionKey(outerKeyB)
	if (!innerA || !innerB || !outerA || !outerB) return null

	const innerMid = {
		x: (innerA.x + innerB.x) / 2,
		y: (innerA.y + innerB.y) / 2,
	}
	const outerMid = {
		x: (outerA.x + outerB.x) / 2,
		y: (outerA.y + outerB.y) / 2,
	}

	const tangentRaw = {
		x: ((innerB.x - innerA.x) + (outerB.x - outerA.x)) / 2,
		y: ((innerB.y - innerA.y) + (outerB.y - outerA.y)) / 2,
	}
	const tangentLength = Math.hypot(tangentRaw.x, tangentRaw.y)
	if (tangentLength <= 1e-6) return null

	const inwardRaw = {
		x: innerMid.x - outerMid.x,
		y: innerMid.y - outerMid.y,
	}
	const inwardLength = Math.hypot(inwardRaw.x, inwardRaw.y)
	if (inwardLength <= 1e-6) return null

	return {
		origin: {
			x: (innerMid.x + outerMid.x) / 2,
			y: (innerMid.y + outerMid.y) / 2,
		},
		tangent: {
			x: tangentRaw.x / tangentLength,
			y: tangentRaw.y / tangentLength,
		},
		inward: {
			x: inwardRaw.x / inwardLength,
			y: inwardRaw.y / inwardLength,
		},
	}
}

const STANDARD_IDS: UniversalRinglockStandardId[] = ['US99', 'US66', 'US411', 'US33', 'US17']

export function planStandardSegmentsForHeight(targetHeightFt: number): UniversalRinglockStandardId[] {
	const safeTargetFt = Math.max(0.1, clampFiniteNumber(targetHeightFt, 10))
	const targetIn = Math.max(1, Math.round(safeTargetFt * 12))

	// User requirement: choose an optimal combination that FITS within the requested height
	// (do not exceed) while strongly preferring larger standards and avoiding silly plans
	// like many small segments just to gain an inch or two.
	//
	// We do this via a DP (unbounded knapsack) but select the final result using a score
	// that penalizes additional segments. This keeps plans "largest-first" in practice.
	//
	// Score = totalHeightIn - (segmentPenaltyIn * (segmentCount - 1))
	// Tie-breaks: higher totalHeightIn, fewer segments, then more/larger parts.
	const segmentPenaltyIn = 24
	const parts = STANDARD_IDS.map((id, idx) => ({
		id,
		idx,
		heightIn: Math.max(1, Math.round(UNIVERSAL_RINGLOCK_STANDARDS[id].heightFt * 12)),
	}))
	const minPartIn = parts.reduce((m, p) => Math.min(m, p.heightIn), Number.POSITIVE_INFINITY)
	if (!Number.isFinite(minPartIn) || parts.length === 0) return ['US66']
	if (targetIn < minPartIn) {
		// If the requested height is shorter than the smallest available standard, we still
		// need *something* to place; use the smallest segment.
		return [parts[parts.length - 1]!.id]
	}

	function vecBetter(a: number[], b: number[] | null): boolean {
		if (!b) return true
		for (let i = 0; i < a.length; i++) {
			if (a[i] !== b[i]) return a[i] > b[i]
		}
		return false
	}

	const bestCount = new Array<number>(targetIn + 1).fill(Number.POSITIVE_INFINITY)
	const bestVec = new Array<number[] | null>(targetIn + 1).fill(null)
	bestCount[0] = 0
	bestVec[0] = new Array(parts.length).fill(0)

	for (let sum = 0; sum <= targetIn; sum++) {
		const c = bestCount[sum]
		const v = bestVec[sum]
		if (!Number.isFinite(c) || !v) continue
		for (let pi = 0; pi < parts.length; pi++) {
			const p = parts[pi]!
			const next = sum + p.heightIn
			if (next > targetIn) continue
			const nextCount = c + 1
			const existingCount = bestCount[next]
			let shouldUpdate = false
			if (nextCount < existingCount) {
				shouldUpdate = true
			} else if (nextCount === existingCount) {
				const candidateVec = v.slice()
				candidateVec[pi] = (candidateVec[pi] ?? 0) + 1
				if (vecBetter(candidateVec, bestVec[next])) {
					bestVec[next] = candidateVec
				}
				continue
			}
			if (shouldUpdate) {
				bestCount[next] = nextCount
				const candidateVec = v.slice()
				candidateVec[pi] = (candidateVec[pi] ?? 0) + 1
				bestVec[next] = candidateVec
			}
		}
	}

	let bestSum = 0
	let bestScore = Number.NEGATIVE_INFINITY
	let bestChosenCount = Number.POSITIVE_INFINITY
	let bestChosenVec: number[] | null = null
	for (let sum = 1; sum <= targetIn; sum++) {
		const c = bestCount[sum]
		const v = bestVec[sum]
		if (!Number.isFinite(c) || !v) continue
		const score = sum - segmentPenaltyIn * Math.max(0, c - 1)
		if (score > bestScore) {
			bestScore = score
			bestSum = sum
			bestChosenCount = c
			bestChosenVec = v
			continue
		}
		if (score < bestScore) continue
		// score tie-breaks
		if (sum > bestSum) {
			bestSum = sum
			bestChosenCount = c
			bestChosenVec = v
			continue
		}
		if (sum < bestSum) continue
		if (c < bestChosenCount) {
			bestChosenCount = c
			bestChosenVec = v
			continue
		}
		if (c === bestChosenCount && bestChosenVec && vecBetter(v, bestChosenVec)) {
			bestChosenVec = v
		}
	}

	const vec = bestVec[bestSum]
	if (!vec) return [parts[parts.length - 1]!.id]

	// Return in bottom-to-top stack order: largest segments first.
	const out: UniversalRinglockStandardId[] = []
	for (let pi = 0; pi < parts.length; pi++) {
		const count = vec[pi] ?? 0
		for (let k = 0; k < count; k++) out.push(parts[pi]!.id)
	}
	return out.length > 0 ? out : [parts[parts.length - 1]!.id]
}

/**
 * Plan stacked standard segments (bottom → top) to ensure we have at least `requiredLiftIndex`
 * standard rosettes available (liftIndex 1..N). This intentionally optimizes for a clean
 * ringlock layout where the top deck can have exactly +2 lifts reserved for guardrails.
 */
export function planStandardSegmentsForRequiredLiftIndex(requiredLiftIndex: number): UniversalRinglockStandardId[] {
	const required = Math.max(1, Math.round(clampFiniteNumber(requiredLiftIndex, 1)))
	const maxRosettes = required + 6 // small overshoot is allowed but strongly discouraged

	const parts = STANDARD_IDS.map((id, idx) => ({
		id,
		idx,
		rosettes: Math.max(1, Math.round(UNIVERSAL_RINGLOCK_STANDARDS[id].rosetteCount)),
	}))

	function vecBetter(a: number[], b: number[] | null): boolean {
		if (!b) return true
		for (let i = 0; i < a.length; i++) {
			if (a[i] !== b[i]) return a[i] > b[i]
		}
		return false
	}

	const bestCount = new Array<number>(maxRosettes + 1).fill(Number.POSITIVE_INFINITY)
	const bestVec = new Array<number[] | null>(maxRosettes + 1).fill(null)
	bestCount[0] = 0
	bestVec[0] = new Array(parts.length).fill(0)

	for (let sum = 0; sum <= maxRosettes; sum++) {
		const c = bestCount[sum]
		const v = bestVec[sum]
		if (!Number.isFinite(c) || !v) continue
		for (let pi = 0; pi < parts.length; pi++) {
			const p = parts[pi]!
			const next = sum + p.rosettes
			if (next > maxRosettes) continue
			const nextCount = c + 1
			const existingCount = bestCount[next]
			let shouldUpdate = false
			if (nextCount < existingCount) {
				shouldUpdate = true
			} else if (nextCount === existingCount) {
				const candidateVec = v.slice()
				candidateVec[pi] = (candidateVec[pi] ?? 0) + 1
				if (vecBetter(candidateVec, bestVec[next])) bestVec[next] = candidateVec
				continue
			}
			if (shouldUpdate) {
				bestCount[next] = nextCount
				const candidateVec = v.slice()
				candidateVec[pi] = (candidateVec[pi] ?? 0) + 1
				bestVec[next] = candidateVec
			}
		}
	}

	let bestSum = required
	let bestExtra = Number.POSITIVE_INFINITY
	let bestChosenCount = Number.POSITIVE_INFINITY
	let bestChosenVec: number[] | null = null
	for (let sum = required; sum <= maxRosettes; sum++) {
		const c = bestCount[sum]
		const v = bestVec[sum]
		if (!Number.isFinite(c) || !v) continue
		const extra = sum - required
		if (extra < bestExtra) {
			bestExtra = extra
			bestSum = sum
			bestChosenCount = c
			bestChosenVec = v
			continue
		}
		if (extra > bestExtra) continue
		if (c < bestChosenCount) {
			bestSum = sum
			bestChosenCount = c
			bestChosenVec = v
			continue
		}
		if (c === bestChosenCount && bestChosenVec && vecBetter(v, bestChosenVec)) {
			bestSum = sum
			bestChosenVec = v
		}
	}

	const vec = bestVec[bestSum]
	if (!vec) return ['US66']
	const out: UniversalRinglockStandardId[] = []
	for (let pi = 0; pi < parts.length; pi++) {
		const count = vec[pi] ?? 0
		for (let k = 0; k < count; k++) out.push(parts[pi]!.id)
	}
	return out.length > 0 ? out : ['US66']
}

export type StandardPlan = {
	segments: UniversalRinglockStandardId[]
	/** Lift indices (rosette liftIndex) where ledgers should be placed. */
	ledgerLiftIndices: number[]
	/** Working deck lift indices (0,4,8,...) selected top-down and clamped to fit under height. */
	workingDeckLiftIndices: number[]
	/** Highest selected working deck lift index, or null when none fit. */
	topWorkingDeckLiftIndex: number | null
	/** Lift index that standards must support (top deck + 2 lifts for guardrails). */
	requiredStandardLiftIndex: number
}

export function computeWorkingDeckLiftIndices(params: {
	/** Height input semantics: absolute world Z of the TOP working deck. */
	heightFt: number
	plankedLevelsCount: number
	includeBaseDeck: boolean
	jackExtensionIn: number
	showWoodSill: boolean
	showBaseCollar: boolean
}): number[] {
	const safeHeightFt = Math.max(0.1, clampFiniteNumber(params.heightFt, 10))
	const requested = Math.max(0, Math.round(clampFiniteNumber(params.plankedLevelsCount, 1)))
	if (requested <= 0) return []

	// Use a tall "virtual" stack so we can map liftIndex → world Z without depending on the real plan.
	const virtualSegments: UniversalRinglockStandardId[] = new Array(10).fill('US99') as any
	const rosettes = computeRosettePositions(
		new THREE.Vector3(0, 0, 0),
		virtualSegments.map(partNumber => ({ partNumber })),
		params.jackExtensionIn,
		params.showWoodSill,
		params.showBaseCollar,
	)

	const zByLift = new Map<number, number>()
	for (const r of rosettes) zByLift.set(r.liftIndex, r.position.z)
	const maxLiftIndex = rosettes.reduce((m, r) => Math.max(m, r.liftIndex), 0)

	const candidates: number[] = []
	if (params.includeBaseDeck && params.showBaseCollar) candidates.push(0)
	for (let li = 4; li <= maxLiftIndex; li += 4) candidates.push(li)

	const fittable = candidates.filter(li => {
		const z = zByLift.get(li)
		return typeof z === 'number' && z <= safeHeightFt + 1e-6
	})
	if (fittable.length === 0) return []

	// Select top-down, clamp to what fits.
	const desc = fittable.slice().sort((a, b) => b - a)
	const selected = desc.slice(0, requested)
	selected.sort((a, b) => a - b)
	return selected
}

export function computeLedgerLiftIndices(params: {
	segments: UniversalRinglockStandardId[]
	/** Height input semantics: absolute world Z under which we place internal ledgers. */
	targetHeightFt: number
	ledgerEveryN: number
	jackExtensionIn: number
	showWoodSill: boolean
	showBaseCollar: boolean
}): number[] {
	const { segments, targetHeightFt, ledgerEveryN, jackExtensionIn, showWoodSill, showBaseCollar } = params
	const everyN = Math.max(1, Math.round(ledgerEveryN))
	const safeTargetHeightFt = Math.max(0.1, clampFiniteNumber(targetHeightFt, 10))

	const standardSegments = segments.map(partNumber => ({ partNumber }))
	// IMPORTANT: `targetHeightFt` is interpreted as an absolute world Z (top of working deck).
	const maxZ = safeTargetHeightFt + 1e-6

	const rosettes = computeRosettePositions(
		new THREE.Vector3(0, 0, 0),
		standardSegments,
		jackExtensionIn,
		showWoodSill,
		showBaseCollar,
	)

	const maxLiftIndex = rosettes
		.filter(r => r.position.z <= maxZ)
		.reduce((m, r) => Math.max(m, r.liftIndex), 0)

	// User requirement: start at the base-collar rosette (liftIndex=0) when present,
	// then place ledgers every N rosettes upward: 0, N, 2N, ...
	const startLiftIndex = showBaseCollar ? 0 : 1

	const liftIndices: number[] = []
	for (let liftIndex = startLiftIndex; liftIndex <= maxLiftIndex; liftIndex += everyN) {
		liftIndices.push(liftIndex)
	}
	return liftIndices
}

export function buildStandardPlan(params: {
	/** Height input semantics: absolute world Z of the TOP working deck. */
	heightFt: number
	ledgerEveryN: number
	plankedLevelsCount?: number
	includeBaseDeck?: boolean
	jackExtensionIn: number
	showWoodSill: boolean
	showBaseCollar: boolean
}): StandardPlan {
	const workingDeckLiftIndices = computeWorkingDeckLiftIndices({
		heightFt: params.heightFt,
		plankedLevelsCount: clampFiniteNumber(params.plankedLevelsCount, 1),
		includeBaseDeck: !!params.includeBaseDeck,
		jackExtensionIn: params.jackExtensionIn,
		showWoodSill: params.showWoodSill,
		showBaseCollar: params.showBaseCollar,
	})
	const topWorkingDeckLiftIndex = workingDeckLiftIndices.length > 0 ? Math.max(...workingDeckLiftIndices) : null
	const requiredStandardLiftIndex = topWorkingDeckLiftIndex !== null ? topWorkingDeckLiftIndex + 2 : 2

	// Plan standards to *support* the top deck +2 guardrail lifts. This is intentionally not
	// a "fit within height" problem anymore; height is the deck elevation, not the top standard.
	const segments = planStandardSegmentsForRequiredLiftIndex(requiredStandardLiftIndex)

	const ledgerLiftIndices = computeLedgerLiftIndices({
		segments,
		targetHeightFt: params.heightFt,
		ledgerEveryN: params.ledgerEveryN,
		jackExtensionIn: params.jackExtensionIn,
		showWoodSill: params.showWoodSill,
		showBaseCollar: params.showBaseCollar,
	})

	return {
		segments,
		ledgerLiftIndices,
		workingDeckLiftIndices,
		topWorkingDeckLiftIndex,
		requiredStandardLiftIndex,
	}
}
